### PR TITLE
Tiny clarification to the problem statement

### PR DESCRIPTION
**Pull request by tuukkamustonen**
See #3.

### CODE REVIEW

**Comment by arusahni** [comment]
I feel that keeping the term pre-forking is important as it is the correct term to use for web servers that spawn a process for each request. What you could do is add a parenthetical to add the clarification you want. For example, "in a pre-forking environment (i.e. with multiple processes)"

**Comment by tuukkamustonen** [comment]
> I feel that keeping "pre-forking" is important, as it is the correct term to use for web servers that spawn a process for each request

I didn't know there are such servers. Sounds quite heavy on resources and slow?

> What you could do is introduce a parenthetical to add the clarification you want. For example, "in a pre-forking environment (i.e. with multiple processes)"

I still don't understand why we should keep "pre-forking" word there - it's just one example of an environment that encounters the problem. You could as well run a non-pre-forking environment with multiple processes and face the same issue. Just stating "multi process" covers all use cases.

If anything I would add "(e.g. a pre- or post-forking web server)" as clarification?

**Comment by arusahni** [comment]
> I didn't know there are such servers. Sounds quite heavy on resources and slow?

It is generally faster, but consumes more memory. [uwsgi](https://uwsgi-docs.readthedocs.io/en/latest/) is a popular pre-forking server used by the Python community.

> I still don't understand why we should keep "pre-forking" word there

The sentence in question is an example that details a very common use case, hence the usage of "for example".  I'd support rephrasing this by shuffling the sentence and swapping in a multiprocessing reference while demoting the pre-forking example:

"These file handlers are thread-safe, but not process-safe, so, if you're attempting to write to a common log file from multiple processes (e.g. a pre-forking web server) you run the risk of your workers trampling over each other."

**Comment by tuukkamustonen** [comment]
> It is generally faster, but consumes more memory. uwsgi is a popular pre-forking server used by the Python community.

Yeah I'm actually running uwsgi but with `lazy-apps` so in post-forking mode.

I just hit my eye on:

>  spawn a process for each request

You don't have to spawn a new process for each request if you run pre-forking. Although uwsgi does support automatically scaling the amount of workers, I don't think it does that. I guess I'm wrong here.

> "These file handlers are thread-safe, but not process-safe, so, if you're attempting to write to a common log file from multiple processes (e.g. a pre-forking web server) you run the risk of your workers trampling over each other."

Ok I added a new PR with that #5. Closing this...

**Pull request closed without merging**
